# Generated by Django 5.2.1 on 2025-07-25 20:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcatagory',
            name='id',
            field=models.CharField(default=api.models.generate_unique_id, editable=False, max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subbookcategory',
            name='id',
            field=models.CharField(default=api.models.generate_unique_id, editable=False, max_length=4, primary_key=True, serialize=False),
        ),
    ]
