# Generated by Django 5.2.1 on 2025-07-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_profile_picture_user_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_pro',
        ),
    ]
