# Generated by Django 5.2.1 on 2025-07-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_is_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
    ]
