# Generated by Django 5.2.1 on 2025-07-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_project_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, null=True),
        ),
    ]
