# Generated by Django 5.2.1 on 2025-07-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
