# Generated by Django 5.2.1 on 2025-07-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_project_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, help_text='Banner or cover image', null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField()),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(default='About Us', max_length=255)),
                ('subtitle', models.TextField(help_text='Brief intro or header')),
                ('mission', models.TextField(help_text='Institution or company mission')),
                ('why_choose_us', models.TextField(help_text='Why students or customers should choose this institution')),
                ('description', models.TextField(blank=True, help_text='Full detailed description or history')),
                ('services', models.TextField(blank=True, help_text='Comma-separated list of services (e.g., Library, Lab, Dormitory)')),
                ('recognition', models.TextField(blank=True, help_text='Awards, certifications, accreditations, etc.')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('role', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
