# Generated by Django 5.2.1 on 2025-07-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_aboutus_teammember_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, help_text='Banner or cover image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
