# Generated by Django 5.2.7 on 2025-10-07 09:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_payment_userpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='qcategory',
            name='enrolled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qcategory',
            name='icon',
            field=models.CharField(default='📚', max_length=50),
        ),
        migrations.AddField(
            model_name='qcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='time',
            field=models.IntegerField(default=30, help_text='Exam duration in minutes'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UserSubjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='For unauthenticated users', max_length=100, null=True)),
                ('progress', models.IntegerField(default=0, help_text='Percentage completed (0-100)')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('score', models.FloatField(blank=True, help_text='Latest exam score', null=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Subject Progress',
                'unique_together': {('session_key', 'subject'), ('user', 'subject')},
            },
        ),
    ]
