# Generated by Django 5.2.7 on 2025-11-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_uploadedpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubjectprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubjectprogress',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubjectprogress',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersubjectprogress',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
