# Generated by Django 5.2.7 on 2025-11-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_usersubjectprogress_progress_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='userpurchase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hard', 'Hard Copy (Physical Book)'), ('soft', 'Soft Copy (Digital Book)'), ('both', 'Both Available')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup Only'), ('delivery', 'Delivery Only'), ('both', 'Pickup & Delivery')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='hard_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for hard copy', max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='is_for_rent',
            field=models.BooleanField(default=False, help_text='Available for rental'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_for_sale',
            field=models.BooleanField(default=True, help_text='Available for purchase'),
        ),
        migrations.AddField(
            model_name='book',
            name='rental_price_per_week',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rental price per week', max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='soft_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for soft copy', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('purchase_hard', 'Purchase Hard Copy'), ('purchase_soft', 'Purchase Soft Copy'), ('rental', 'Rental'), ('extension', 'Rental Extension')], default='purchase_soft', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='rental_duration_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpurchase',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpurchase',
            name='purchase_type',
            field=models.CharField(choices=[('hard', 'Hard Copy'), ('soft', 'Soft Copy')], default='soft', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='userpurchase',
            unique_together={('user', 'book', 'purchase_type')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['book_type'], name='api_book_book_ty_862811_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_for_sale', 'is_for_rent'], name='api_book_is_for__de19c5_idx'),
        ),
    ]
