# Generated by Django 5.2.7 on 2025-11-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual Seller'), ('company', 'Company'), ('publisher', 'Publisher'), ('bookstore', 'Bookstore'), ('educational', 'Educational Institution'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('decade', '10-Year')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('telebir', 'Telebir'), ('cbe_bir', 'CBE Bir'), ('hellocash', 'HelloCash'), ('dashen', 'Dashen Bank'), ('awash', 'Awash Bank'), ('amole', 'Amole'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('chapa', 'Chapa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Admin', 'Admin'), ('Seller', 'Seller'), ('Buyer', 'Buyer')], max_length=10, null=True),
        ),
    ]
